grindery-io/grindery-bot-auth

- src/scripts/patchwallet.js
This pull request adds the script responsible for populating the `patchwallet` field in the MongoDB database for specific users. The script uses the `getPatchWalletAddressFromTgId` function to fetch and update the PatchWallet addresses.
The `updatePatchWalletAddresses` function performs the following tasks:
- Establishes a connection to a MongoDB database.
- Retrieves "users" collection from the database.
- Iterates through users with empty "patchwallet" fields.
- Calls the `getPatchWalletAddressFromTgId` function to fetch PatchWallet addresses based on Telegram IDs.
- Updates user documents with the obtained PatchWallet addresses.
- Logs updates and errors.
- Exits the script upon completion.
> add patchwallet script to fill missing addresses in db

- package-lock.json
- package.json
- src/routes/db.js
- src/scripts/rewards.js
- src/scripts/transfers.js
- src/utils/patchwallet.js
- yarn.lock
This PR introduces two scripts for user reward distribution.
- Distributes a sign-up reward of 100 Grindery One Tokens to users without previous rewards.
- Identifies eligible users based on their reward history.
- Distributes referral rewards of 50 Grindery One Tokens to senders of eligible transactions.
- Ensures that rewards are not duplicated for the same transaction.
> add script for missing rewards

- src/router.js
- src/routes/leaderboard.js
Fetch the top 5 users who sent the most transactions over the last 7 days, second page (assuming a limit of 10 per page):
`v1/tx-sent?days=7&topX=5&limit=10&skip=10`
Fetch the top 6 users who sent the most tokens over the last 15 days, third page (assuming a limit of 10 per page):
`v1/tokens-sent?days=15&topX=6&limit=10&skip=20`
Fetch the top 7 users with the highest reward accumulation over the last 30 days, fourth page (assuming a limit of 10 per page):
`v1/rewards?days=30&topX=7&limit=10&skip=30`
> Leaderboard Endpoint

- src/utils/webhook.js
This PR contains webhook POST requests to FlowXO in order to inform users when the following events happen:
- New user
- New sign up reward
- New referral reward
- New transaction
> add calls to FlowXO webhooks in webhook utils

- src/routes/webhook.js
New event to send multiple events.
- Make it easier for the user to send 1 G1 (or another amount) in a single click to their contacts who are not yet Grindery users only (filter).
- Once these tokens are sent, have access to all users who are not yet users despite sending them to notify them of reminders.
[POST] `/v1/webhook`
Multiple events request:
```
[
{
"event": "event_name1",
"params": { "param1": "value1" }
},
{
"event": "event_name2",
"params": { "param1": "value2" }
},
{
"event": "event_name3",
"params": { "param1": "value3" }
},
{
"event": "event_name4",
"params": { "param1": "value4" }
},
{
"event": "event_name5",
"params": { "param1": "value5" }
}
]
```
Multiple events response:
```
[
{
"success": true,
"messageId": "8852700785693732"
},
{
"success": true,
"messageId": …
```
> send transfers in batch

- src/test/pubsub-new-transaction.test.js
- src/utils/webhook.js
This PR contains a patch which makes it possible to detect 470 errors when receiving the PatchWallet status and to exit the queue with a failure immediately if this situation occurs rather than entering the queue again because the result will be identical.
> handling 470 error for patchwallet status endpoint

- src/routes/analytics.js
- src/routes/bot_data.js
- src/routes/db.js
- src/routes/leaderboard.js
- src/routes/support.js
- src/scripts/patchwallet.js
- src/scripts/rewards.js
- src/scripts/segment.js
- src/scripts/transfers.js
- src/scripts/users.js
- src/utils/transfers.js
This PR focuses on:
- Always use dedicated constants to get collection names.
- Clean up unused imports.
> refactor: always use constant for collection names and clean up

- src/test/pubsub-new-transaction.test.js
- src/utils/webhooks/webhook.js
This PR fix a bug in `handleNewTransaction`: the function should not add anything in database if sender is not a user.
> feat: `handleNewTransaction`should not add anything in db if sender not user

- src/router.js
- src/routes/users.js
This pull request introduces two new routes:
- Handles the update of user attributes based on the provided request body.
- Expects an array of attribute objects in the request body.
- Validates the structure of each object within the array (`userTelegramID`, `attributeNames`, `erased_others`).
- Updates the MongoDB collection accordingly, either overwriting existing attributes or adding new ones without duplicating based on the `erased_others` flag.
- Retrieves the attributes of a user based on their `userTelegramID` sent as a query parameter.
- Validates the presence of the `userTelegramID` in the query.
- Searches the MongoDB collection for the user and returns their attributes if found.
> feat: add user attributes route

- src/test/pubsub-new-transaction.test.ts
- src/utils/segment.ts
- src/utils/transfers.ts
- src/utils/webhooks/transaction.ts
> chore: add token symbol

- src/scripts/bigquery.ts
- src/scripts/cronjob.ts
Ths PR changes the time threshold when searching `tranfers` and `users`.
The time is being reduced to not overload the servers with 24 hours time range, and with 4 hours time range even if it fails will have next 3 attempts (run every each hour).
> refact: decrease hours in script when searching

- src/test/pubsub-reward.test.ts
- src/types/webhook.types.ts
- src/utils/webhooks/webhook.ts
This pull request introduces boolean flags to handle individual reward cuts, enhancing the flexibility and control over specific reward types. The addition of these flags enables precise control and customization when managing rewards.
> feat: add boolean flags to cut rewards individually

- src/test/pubsub-isolated-reward.test.ts
- src/test/pubsub-link-reward.test.ts
- src/test/pubsub-new-transaction.test.ts
- src/test/pubsub-new-vesting.test.ts
- src/test/pubsub-referral-reward.test.ts
- src/test/pubsub-reward.test.ts
- src/test/pubsub-signup-reward.test.ts
- src/test/pubsub-swap.test.ts
- src/test/utils.ts
- src/test/vesting.test.ts
This pull request introduces a new type, `ContractStub`, providing a structured representation for contract stubs within the codebase. The `ContractStub` type encapsulates contract methods, allowing for clearer definition and maintenance of contract-related structures.
> type: add a type for Contract Stubs

- src/test/pubsub-reward.test.ts
- src/test/utils.ts
This pull request introduces a new type, `RewardStub`, specifically defining the structure of a `SinonStub` used to represent the reward function stub within the codebase.
> type: add `RewardStub` type

- src/test/pubsub-new-transaction.test.ts
- src/test/pubsub-swap.test.ts
- src/utils/constants.ts
- src/utils/swap.ts
- src/utils/transfers.ts
- src/webhooks/utils.ts
This pull request introduces a new feature to enhance the error handling mechanism for transactions and swaps. It includes the addition of a specific failure code, 503 from PatchWallet, in the database to accurately capture and manage error cases related to service unavailable responses.
Incorporating this new failure code will provide better insight into and management of these specific failure scenarios during transactions and swaps.
> feat: add new 503 failure code in database for transactions and swaps

- .github/workflows/ci.yml
- package-lock.json
- package.json
- src/routes/tge.ts
- src/routes/webhook.ts
- src/test/tge.test.ts
- src/test/utils.ts
- src/utils/constants.ts
This PR introduces new routes for handling TGE pre-orders. It includes endpoint setups and necessary logic to enable users to initiate pre-orders for token purchases during the TGE phase.
> feat: add routes for tge pre order

- src/utils/chains.ts
This PR removes the chain name as a key in the chain mapping for the EIP-155 convention.
> feat: remove chain name as key in chain mapping for eip155 convention

- src/types/hedgey.types.ts
- src/types/mongo.types.ts
- src/types/webhook.types.ts
- src/utils/patchwallet.ts
- src/utils/telegram.ts
- src/utils/user.ts
- src/webhooks/isolated-reward.ts
- src/webhooks/link-reward.ts
- src/webhooks/referral-reward.ts
- src/webhooks/signup-reward.ts
- src/webhooks/swap.ts
- src/webhooks/transaction.ts
- src/webhooks/utils.ts
- src/webhooks/vesting.ts
Using the generic bson `Document` type:
```typescript
/** @public */
export declare interface Document {
[key: string]: any;
}
```
is quite unsafe because it connects keys of type `string` to values of type  `any`. So there is no precise way to verify, for example, that the fields really exist (and are of a correct type) at the location concerned.
So, I created specific types which group together all the fields that we have in each of our collections in order to type all our interactions with the database in a secure manner.
> feat: replace generic `Document` type by proper Mongo types

- mocha.mocharc.cjs
- src/test/validators/webhooks.validator.test.ts
- src/test/validators/webhooks.validator.utils.test.ts
- src/validators/utils.ts
- src/validators/webhooks.validator.ts
At the moment, Telegram user IDs are only validated on the basis that they must be strings. 
But with the description given here https://core.telegram.org/type/long, we can do a much more precise validation, in order to ensure, for example, that Ethereum addresses or random strings can never enter while waiting for a user ID.
Added a new utility method `validateUserTelegramID` along with corresponding unit tests to ensure accurate validation of user Telegram IDs.
- Implemented `validateUserTelegramID` utility method to validate user Telegram IDs.
- Included thorough unit tests to verify the functionality and edge cases of the new utility method.
> feat: add `validateUserTelegramID` util method and unit tests

- src/test/webhooks/pubsub-new-order-g1.test.ts
- src/test/webhooks/pubsub-new-order-usd.test.ts
- src/webhooks/order.ts
Addresses an edge case where the G1 payment of a quote succeeds, but the USD payment fails. In such a scenario, the user should be allowed to retry the USD payment for the same quote without initiating a new payment for a different quote. This pull request introduces improvements to handle this specific edge case.
> Enhancement: Handle Edge Case for Quote Payment Retry

- src/routes/tge.ts
- src/test/tge/tge.test.ts
This pull request introduces a hardcap for USD investment, ensuring that the investment amount does not exceed $10,000 USD. The validation has been added to the relevant part of the code to enforce this limit.
- Added a check to ensure that the equivalent USD invested does not exceed $10,000 USD.
- Improved error messaging for cases where the hardcap is not met.
> add hardcap for USD investment

- src/routes/tge.ts
- src/test/tge/tge.test.ts
- src/utils/g1gx.ts
Introduces a balance check fail-safe mechanism before generating a quote in the `/quote` route. This enhancement ensures that the user's G1 and token balances are verified to prevent insufficient balance scenarios. The fail-safe logic includes checks for G1 balance, token balance (if applicable), and a maximum USD investment limit.
- Added G1 balance check to ensure it's sufficient for the requested token amount.
- Implemented token balance check (if chainId and tokenAmount are provided) to prevent insufficient token balance scenarios.
> add balance check fail safe before quote
