src/routes/bot_auth.js
Replaced `phone` param with `user_id` in auth init endpoint. 
Modified callback endpoint, now it is saving user_id, response path, and patchwallet address obtained for `grindery:user_id` to HubSpot.
Added param to `init` endpoint to specify custom success redirect url.
=> update auth endpoints

src/router.js, src/routes/support.js
Import a list of users into the database. Each user should contain necessary fields. This endpoint will reject the insertion if a user already exists in the database.
POST `v1/support/import`
Request Body Example:
```
[
{
"UserID": "1",
"FirstName": "Mauricio",
"UserHandle": "mau_dev",
"ResponsePath": "some-path",
"wallet": "some-wallet"
},
{
"UserID": "533",
"FirstName": "Mauricio",
"UserHandle": "mau_dev",
"ResponsePath": "some-path",
"wallet": "some-wallet"
}
]
```
The endpoint maps the attributes from JSON request to the ones we are currently using in users mongodb collection
```
const userFormatted = {
userTelegramID: entry.UserID,
userName: entry.FirstName,
userHandle: entry.UserHandle,
responsePath: entry.ResponsePath,
patchwallet: entry.wallet,
dateAdded: new Date().toISOString(), …
```
=> add import route

src/db/conn.js, src/routes/db.js
This PR contains additional optional `limit` and `start` query parameters in GET route by collection name for `/db` in order to be able to:
- Offset the start of the result array.
- Limit the number of results in the result array.
=> add optional start and limit to get by collection name

src/scripts/rewards.js
The `updateRewardMessages` function is responsible for updating reward messages in a MongoDB collection. It iterates through each reward document in the collection, checks the reward amount and message content, and updates the message accordingly. This function ensures that rewards have consistent and descriptive messages based on their attributes.
- Message Updates:
- If the `amount` is "100" the message is updated to "Sign up reward."
- If the `amount` is "50" and the message includes "Product Hunt," the message becomes "Product Hunt reward."
- If the `amount` is "50" and the message does not include "Product Hunt," the message is set to "Referral reward."
- If none of the above conditions match, the message is updated to "2x Referral reward."
- Bulk Write: Updated reward documents are …
=> add script `updateRewardMessages`

package-lock.json, src/routes/webhook.js, src/utils/constants.js, src/utils/patchwallet.js, src/utils/segment.js, src/utils/webhook.js, yarn.lock
This PR contains the logic implementation for the following events in pubsub context:
- `new_user`: new user is added to the database.
- `new_signup_reward`: sign up reward of 100 G1 is distributed to a new user who is then added to the database.
- `new_referral_reward`: a referral reward of 50 g1 is distributed to all people who sent G1 to a new user who is then added to the database.
- `new_transaction`: a new transaction is done and added to the database.
=> add logic for events in pubsub

src/test/hooks.js, src/test/utils.js, src/utils/constants.js, src/utils/webhook.js
This PR contains the migration of all collections of the database to the production version for the entire PubSub implementation and unit tests.
=> switch collections to production for pub sub

src/test/pubsub-new-transaction.test.js, src/utils/webhook.js, yarn.lock
This PR contains better support for 470 PatchWallet errors so as not to replay these failed transactions (certainly due to a lack of balance) infinitely.
=> Handle Patchwallet error 470 in `handleNewTransaction`

src/routes/db.js, src/utils/transfers.js
This PR adds formatting for transactions made to new users and for users who entered Grindery via the referral link.
=> Formatting for transactions and rewards

src/test/pubsub-referral-reward.test.js, src/test/pubsub-signup-reward.test.js, src/utils/webhook.js
=> Combine `handleSignUpReward` and `handleReferralReward` function parameters into a single object

src/utils/rewardHelpers.js, src/utils/webhook.js
=> refact: fn utility updating referral reward

src/utils/rewardHelpers.js, src/utils/webhook.js
=> refact: utility inserting referral reward

src/utils/user.js, src/utils/webhook.js
=> implement `User` class

src/routes/webhook.js, src/test/pubsub-isolated-reward.test.js, src/test/pubsub-link-reward.test.js, src/test/pubsub-new-transaction.test.js, src/test/pubsub-referral-reward.test.js, src/test/pubsub-reward.test.js, src/utils/user.js, src/utils/webhooks/isolated-reward.js, src/utils/webhooks/webhook.js
This PR focuses on the addition of isolated rewards with special reasons, amounts and messages.
=> Add a special treatment for isolated rewards

src/router.js, src/routes/analytics.js
This PR adds a route to get the number of transactions in the last hour.
=> feat: add endpoint to get number txs during last hour

src/routes/bot_data.js
This PR secures balance endpoint by adding some important verifications to avoid any potential errors.
=> feat: secure GET balance endpoint

src/routes/webhook.js, src/test/pubsub-new-transaction.test.js, src/utils/segment.js, src/utils/transfers.js, src/utils/webhooks/transaction.js, src/utils/webhooks/webhook.js
This PR focuses on:
- Adding a `TransferTelegram` class to simplify `handleNewTransaction` operations (update of the database, status check....).
- Refactoring `handleNewTransaction` to avoid too verbose implementation.
- Moving `handleNewTransaction` function to a dedicated file in order to decouple our implementations and clean up everything.
=> feat: add a `TransferTelegram` class

package-lock.json, package.json, src/index.js, src/scripts/bigquery.js, src/scripts/cronjob.js
=> chore: add cronjob to run scripts

src/scripts/rewards.js, src/scripts/users.js
This PR improves and fix scripts for:
- Distributing missing sign up rewards on a daily basis.
- Distributing missing referral rewards on a daily basis.
=> feat: fix reward scripts

src/scripts/cronjob.js, src/scripts/rewards.js
=> chore: create cronjob

src/routes/bot_data.ts, src/routes/db.ts
This PR focuses on streamlining the project's routing structure by eliminating redundant or unused routes. The removal of unnecessary routes declutters the codebase, enhancing readability, and simplifying maintenance.
**Changes:**
- Removed routes that were not actively used or redundant in the project.
- This PR aims to optimize the routing configuration, ensuring a more concise and maintainable codebase.
=> refactor: remove unnecessary routes

package-lock.json, package.json, src/routes/bot_auth.ts, src/routes/telegram.ts, src/utils/crypt.ts
This PR removes redundant or unused packages from the project dependencies, enhancing its efficiency and reducing unnecessary bloat. The cleanup focuses on streamlining the codebase by removing packages that are no longer utilized, ensuring a leaner and more manageable project structure.
**Changes:**
- Removed redundant packages that were not actively utilized within the project.
- Enhances the project's performance and reduces unnecessary dependencies.
- This PR aims to optimize the project's dependency tree and promote a cleaner codebase.
=> refactor: remove unnecessary packages

src/utils/constants.ts, src/utils/patchwallet.ts, src/utils/rewards.ts
This pull request aims to improve the typing within the PatchWallet utility functions and refactors certain parts for better readability and maintainability.
**Changes Made:**
- Enhanced typing within PatchWallet utility functions.
- Refactored sections in the PatchWallet utility for improved readability and maintainability.
=> refactor: add better typing and refactor patchwallet utils

package-lock.json, package.json, src/test/utils-web3.test.ts, src/utils/web3.ts
This pull request introduces improvements in typing for the web3 utility functions and enhances the existing unit tests for better coverage and reliability.
=> feat: better typing and unit tests for web3 utils

src/test/webhook-utils.test.ts, src/utils/rewards.ts, src/utils/transfers.ts, src/utils/webhooks/isolated-reward.ts, src/utils/webhooks/link-reward.ts, src/utils/webhooks/referral-reward.ts, src/utils/webhooks/signup-reward.ts, src/utils/webhooks/transaction.ts, src/utils/webhooks/utils.ts
This PR aims to improve code organization by encapsulating the status-related utility functions (`isSuccessfulTransaction`, `isFailedTransaction`, `isPendingTransactionHash`) within a dedicated Webhook Utility file. This separation enhances code readability and maintainability by centralizing these functions in a more appropriate and descriptive location.
=> refactor: encapsulate status functions in a webhook util file

src/routes/webhook.ts, src/test/pubsub-new-transaction.test.ts, src/test/webhook-utils.test.ts, src/utils/webhooks/utils.ts
This pull request introduces functionality to handle float number amounts in transactions. The feature enables processing transactions with floating-point values, enhancing the flexibility of the system to accommodate various types of transactions with precise decimal amounts.
The update includes changes in the transaction processing logic to validate and handle floating-point numbers, ensuring accurate processing of such transactions.
=> feat: add float number amounts for transactions

src/routes/analytics.ts, src/routes/leaderboard.ts, src/scripts/rewards.ts, src/test/time.test.ts, src/utils/rewards.ts, src/utils/time.ts, src/utils/transfers.ts, src/utils/webhooks/swap.ts
This PR introduces new time helper functions to facilitate date and time calculations in the codebase. The new functions provide the ability to retrieve dates and times before a specified reference date by a certain number of hours, days, and minutes.
=> feat: add time helpers

src/routes/db.ts, src/routes/webhook.ts, src/utils/rewards.ts, src/utils/transfers.ts, src/utils/webhooks/isolated-reward.ts, src/utils/webhooks/link-reward.ts, src/utils/webhooks/referral-reward.ts, src/utils/webhooks/signup-reward.ts, src/utils/webhooks/transaction.ts, src/utils/webhooks/utils.ts
Currently, certain functions in our codebase might benefit from refactoring to improve code readability, maintainability, and potentially enhance performance.
This issue is dedicated to reviewing and refactoring specific functions within our codebase.
=> refactor: refactor some functions

package.json, src/loadEnvironment.ts, src/routes/users.ts
This pull request introduces a new feature to the system, enabling users to access their USD balance through a dedicated API endpoint.
=> feat: add balance endpoint for users to get USD balance

package-lock.json, package.json, src/loadEnvironment.ts, src/routes/bot_data.ts, src/utils/constants.ts, src/validators/utils.ts, src/validators/withdraw.validator.ts
This PR introduces a new endpoint `/withdraw` to handle withdrawal requests securely. It includes validation for incoming data and authentication to ensure secure transactions.
- Created a new route `/withdraw` in `routes.js` to handle withdrawal requests.
- Implemented input validation using `express-validator` for `tgId`, `recipientwallet`, `amount`, and `tokenAddress`.
- Integrated middleware for API key authentication to secure the endpoint.
- Utilized a custom validator for `amount` to validate that it's a string representing a float greater than zero.
- Input validation added to prevent malformed or malicious requests.
- API key authentication integrated to restrict unauthorized access.
=> feat: add withdraw endpoint with security

src/scripts/bigquery.ts, src/utils/constants.ts
Refactored the codebase to incorporate dedicated constants for BigQuery table IDs. 
This enhancement improves code readability and maintainability by centralizing the definitions of table IDs for BigQuery across the codebase.
=> refactor: add constants for BigQuery table IDs

src/test/pubsub-new-transaction.test.ts, src/test/pubsub-new-vesting.test.ts, src/test/pubsub-swap.test.ts, src/types/hedgey.types.ts, src/types/webhook.types.ts, src/utils/patchwallet.ts, src/webhooks/transaction.ts, src/webhooks/vesting.ts
Issue https://github.com/grindery-io/grindery-bot-auth/issues/133
=> chore: remove chainName

src/types/hedgey.types.ts, src/types/webhook.types.ts, src/utils/constants.ts, src/utils/segment.ts, src/utils/swap.ts, src/utils/transfers.ts, src/utils/vesting.ts
=> types: add better types for Segment calls

src/utils/airtableClient.ts
=> remove old airtable client util

src/routes/linea.ts
This pull request enhances the typing within the Linea route to improve code clarity and maintainability.
=> type: better types for Linea route

src/router.ts, src/routes/tge.ts, src/test/g1gx.test.ts, src/test/time.test.ts, src/utils/g1gx.ts, src/utils/time.ts
- **New Features for G1 to GX Conversion:**
- Implemented a comprehensive conversion function named `computeG1ToGxConversion` within the `utils/g1gx.ts` file.
- The function includes calculations for GX quantities after MVU and time effects, determining USD equivalents, and more.
- **Enhancements:**
- Added extensive documentation for each function involved in the conversion process, improving code readability and comprehension.
- Introduced rigorous unit tests to ensure the accuracy and reliability of the newly added and existing conversion functions.
This pull request addresses the need to establish a reliable method for converting G1 to GX and provides the necessary documentation and tests for maintaining code quality and integrity.
=> feat: add features for G1 to GX conversion

src/utils/rewards.ts, src/utils/swap.ts, src/utils/transfers.ts, src/utils/vesting.ts, src/webhooks/utils.ts
This pull request enhances the typing for transaction statuses across the codebase. It ensures stricter typing and clarity by introducing specific types for transaction statuses where previously typings were ambiguous or less precise (string).
=> types: enforce better typing for transaction status

src/test/pubsub-swap.test.ts, src/utils/chains.ts, src/utils/patchwallet.ts, src/utils/swap.ts
This pull request aims to enhance code readability and maintainability by encapsulating all chain mapping details within a unified structure. 
The refactor involves consolidating multiple chain mapping declarations into a single object, improving organization and ease of access for blockchain information.
=> refactor: encapsulate all chain mapping details inside a single chain mapping

src/routes/db.ts, src/utils/transfers.ts
This pull request introduces comprehensive TypeScript types for the transfer format functions. It includes types for:
- `IncomingTransaction`: Describing the structure of incoming transactions.
- `OutgoingTransaction`: Describing the structure of outgoing transactions.
- `RewardTransaction`: Detailing the structure of reward-related transactions.
These types enhance code clarity, enforce stricter typing, and provide better documentation for the transfer format functions.
=> types: add types for transfers fmt functions

src/routes/tge.ts
* Fixed endpoint path in the docs.
@tcoratger  **Question:** Why POST? We are not writing any data here.
=> fix docs for conversion-information route

src/utils/constants.ts, src/utils/rewards.ts, src/utils/swap.ts, src/utils/transfers.ts, src/utils/vesting.ts, src/webhooks/isolated-reward.ts, src/webhooks/link-reward.ts, src/webhooks/referral-reward.ts, src/webhooks/signup-reward.ts, src/webhooks/swap.ts, src/webhooks/transaction.ts, src/webhooks/utils.ts, src/webhooks/vesting.ts
This pull request aims to enhance code consistency by refactoring the `sendTransactionAction` method across multiple classes. The objective is to streamline the usage of this method and ensure a unified structure for improved maintainability and readability.
=> refactoring `sendTransactionAction` for all classes

src/utils/ankr.ts, src/utils/swap.ts, src/utils/transfers.ts, src/utils/vesting.ts, src/webhooks/isolated-reward.ts, src/webhooks/link-reward.ts, src/webhooks/referral-reward.ts, src/webhooks/signup-reward.ts, src/webhooks/swap.ts, src/webhooks/transaction.ts, src/webhooks/utils.ts, src/webhooks/vesting.ts
This pull request aims to enhance the `getStatus` function for better code consistency and readability. It unifies the error handling and response for `getStatus` by using a consistent approach when dealing with reward, transactions, swaps, vesting and failure cases. Additionally, it refactors the code for improved clarity and simplification.
=> refactor: unify `getStatus` handling

src/routes/tge.ts, src/test/tge.test.ts, src/test/utils.ts
- **Description:** Fetches order and quote details based on the provided order ID.
- **HTTP Method:** GET
- **Response Codes:**
- `200`: Success with the order or quote details.
- `404`: Indicates both order and quote were not found for the given ID.
- `500`: Internal server error in case of any issues during retrieval.
- **Location:** `router.patch('/order')`
- **Purpose:** This added check validates if the order's status is ready for processing USD payments.
- **Condition:**
- Ensures that the order exists and is neither in the status of 'Waiting USD' nor 'Failure USD'.
- **Response:**
- If the order's status is not suitable for USD payment processing, it returns a `400` status with an error message indicating the status is not ready for USD transactions.
=> fix: improve TGE routes

src/test/utils-web3.test.ts, src/utils/web3.ts, src/webhooks/swap.ts
=> chore: wei to ether

src/types/webhook.types.ts, src/webhooks/isolated-reward.ts, src/webhooks/link-reward.ts, src/webhooks/referral-reward.ts, src/webhooks/signup-reward.ts, src/webhooks/swap.ts, src/webhooks/transaction.ts, src/webhooks/utils.ts, src/webhooks/vesting.ts
Added a utility function `handlePendingHash` to manage all pending hash transactions effectively.
This feature introduces a new utility function called `handlePendingHash`. This function is designed to handle various pending hash transactions efficiently by checking the status, duration, and database update requirements. It optimizes the process of managing pending hash transactions within the system.
This addition enhances the system's ability to handle and process pending hash transactions more effectively, ensuring smoother and optimized transaction management.
- Added: `handlePendingHash` utility function
- Purpose: Efficient management of pending hash transactions
- Impact: Enhances transaction handling capabilities by optimizing pending hash processing
This feature significantly …
=> feat: add `handlePendingHash` util to handle all pending hash txs

src/test/validators/webhooks.validator.test.ts, src/test/validators/webhooks.validator.utils.test.ts, src/validators/utils.ts, src/validators/webhooks.validator.ts
closes https://github.com/grindery-io/grindery-bot-auth/issues/193#issue-2070626799
=> chore: chain id validator

src/routes/tge.ts, src/routes/users.ts, src/test/tge/g1gx.test.ts, src/test/tge/tge.test.ts, src/test/utils/time.test.ts, src/test/validators/webhooks.validator.utils.test.ts, src/utils/g1gx.ts, src/utils/time.ts
This pull request aims to update the end date of TGE and retrieve the MVU score from the database.
- Updated the end date of TGE to reflect the correct timeframe.
- Implemented functionality to fetch the MVU score from the database.
- **Updated End Date**: The TGE end date was previously inaccurate and has been rectified to reflect the correct period (15.01.2024).
- **MVU Score Retrieval**: Added functionality to retrieve the MVU score directly from the database for improved accuracy.
=> get MVU score from database and change end date

src/test/validators/webhooks.validator.test.ts, src/test/validators/webhooks.validator.utils.test.ts, src/validators/utils.ts, src/validators/webhooks.validator.ts
This pull request introduces a new utility function `validateAddress` within the validators module. The function is designed to validate blockchain addresses using `express-validator` and `Web3`.
- Added `validateAddress` function to validators module.
- Created validation logic for checking the validity of blockchain addresses.
- Implemented the function to leverage `express-validator` and `Web3` utility functions.
=> add `validateAddress` utils for validators

src/test/validators/webhooks.validator.test.ts, src/test/validators/webhooks.validator.utils.test.ts, src/validators/utils.ts, src/validators/webhooks.validator.ts
This pull request adds a new utility function, `validateAmount`, aimed at validating amounts.
- Created a new function `validateAmount` in the validator utils.
- Implemented the function to verify if the provided value is a string representing a positive float value.
The purpose of this addition is to enhance the validation capabilities of the application by incorporating a dedicated validator for checking amounts.
=> add `validateAmount` validator util to validate amounts

src/utils/user.ts, src/webhooks/webhook.ts
Utilizing the `build` asynchronous method for generating instances of `UserTelegram`.
Implemented the `build` method in the `UserTelegram` class to handle the creation of a `UserTelegram` instance asynchronously. This change ensures a streamlined and consistent approach for creating instances, providing better control over asynchronous operations during instance initialization.
=> use `build` async method to create `UserTelegram` instance

src/webhooks/isolated-reward.ts, src/webhooks/link-reward.ts, src/webhooks/referral-reward.ts, src/webhooks/signup-reward.ts, src/webhooks/swap.ts, src/webhooks/transaction.ts, src/webhooks/utils.ts, src/webhooks/vesting.ts
This pull request enhances the handling of the user operation hash (`userOpHash`) and improves the management of the pending hash status within the codebase.
- Improved conditional handling of the `userOpHash` update within reward telegram instances.
- Enhanced handling and management of the pending hash status.
- Refactored related functions for better readability and efficiency.
=> better handling user op hash and pending hash status

src/routes/users.ts, src/test/routes/users.test.ts
This pull request aims to enhance the `POST /attributes` endpoint functionality. The primary improvements include:
1. **Better Validation:** Improved validation checks for the request body to ensure it contains a valid array of attribute objects.
2. **Enhanced Documentation:** Updated Swagger documentation to provide clearer examples and descriptions for both request and response scenarios.
3. **Consistent Naming:** Ensured consistent naming conventions for properties in the request body, using `userTelegramID` and `attributes`.
4. **Refactor Code:** Minor code refactoring for better readability and maintainability.
- Improved validation checks for the request body.
- Enhanced Swagger documentation with clear examples.
- Ensured consistent naming conventions for properties.
=> improve POST attributes endpoint

src/test/utils/user.test.ts, src/test/webhooks/pubsub-reward.test.ts, src/types/mongo.types.ts, src/types/tests.types.ts, src/types/webhook.types.ts, src/utils/user.ts, src/webhooks/isolated-reward.ts, src/webhooks/link-reward.ts, src/webhooks/referral-reward.ts, src/webhooks/signup-reward.ts, src/webhooks/webhook.ts
This pull request adds a new `UserTelegram` class to handle existing users on the Telegram platform. Additionally, it includes unit tests to ensure the proper functioning of the class.
- Added `UserTelegram` class with necessary properties and methods.
- Implemented unit tests to validate the behavior of the class.
=> add a `UserTelegram` class for existing users and unit tests

src/routes/tge.ts, src/test/tge/tge.test.ts
This pull request adds a condition to block the G1 amount of 0 in the `GET /quote` route. Additionally, it includes a unit test to ensure that this condition is working as expected.
- Added a condition to check if the G1 amount is a positive number in the `GET /quote` route.
- If the G1 amount is 0 or a negative number, a 404 response is returned with an appropriate error message.
- Included a new unit test to validate the behavior of blocking G1 amounts of 0.
=> add condition to block G1 amount of 0 with unit test in GET /quote route
